# Generated by Django 3.0.3 on 2020-02-12 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_api.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=5000)),
                ('review_text', models.CharField(max_length=10000)),
                ('region', models.CharField(max_length=20)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_api.Business')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=20)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_api.Review')),
            ],
        ),
        migrations.CreateModel(
            name='OffensiveText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense', models.CharField(max_length=20)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_api.Review')),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=20)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_api.Review')),
            ],
        ),
    ]
