# Generated by Django 3.0.3 on 2020-02-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_api', '0002_auto_20200213_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='angry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='joy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='love',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='surprise',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='positive',
            field=models.IntegerField(default=0),
        ),
    ]
