# Generated by Django 3.0.3 on 2020-02-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_api', '0003_auto_20200213_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
