# Generated by Django 3.0.3 on 2020-02-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_api', '0004_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='offense',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='review_api.Business'),
        ),
    ]
